
# default
set -g default-terminal xterm-256color
# vi keybinds in copy mode
set -g status-keys vi
# window and pane index starts at 1
set -g base-index 1
setw -g pane-base-index 1
# mouse support
set -g mouse on
# window name set to current process
setw -g automatic-rename on
set -g set-titles on
set -g set-titles-string "#T"
# renumber windows on close
set -g renumber-windows on

# keybinds
set-option -g prefix M-Space

# moving between panes and windows does not require prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n S-Left  previous-window
bind -n S-Right next-window

# window split
bind-key v split-window -h
bind-key h split-window -v

# move window
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# config reload
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# sync
bind-key y set-window-option synchronize-panes\; display-message "Sync toggled..."

# Lengthen the amount of time status messages are displayed
set-option -g display-time 2000
set-option -g display-panes-time 2000

# Theme
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 60
set -g status-right-length 150
set -g status-bg default
set -g status-fg colour250
set -g status-style fg=colour250
set -g pane-border-style fg=colour236
set -g pane-active-border-style fg=blue,bold

# --- Left Side: Session + spacing + windows ---
set -g status-left "#[fg=blue][Session: #S]#[default]    "

# Window list format
setw -g window-status-format "#[fg=blue]#I:#W#[default]"
setw -g window-status-current-format "#[fg=blue,bold][#I:#W]#[default] "

# --- Right Side: Application + IP + Time ---
set -g status-right "\ 
\#[fg=#FF928B,bg=default] #(ps -o comm= -t $(tmux display-message -p '#{pane_tty}' | sed 's:/dev/::') 2>/dev/null | tail -n1 || echo bash) #[default] \ 
\#[fg=#F49E4C,bg=default] #h@#(hostname -I | awk '{print \$1}') #[default] \ 
\#[fg=#F6EFA6,bg=default] %m/%d/%Y #[default]"

# Change table color when acitivty occurs, do not reset when stopped.
setw -g monitor-activity on
setw -g monitor-silence 0
