[mgr]
ratio = [1,3,2]
sort_by = "extension"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "mtime"
show_hidden = false
show_symlink = true
scrolloff = 10

[preview]
wrap = "yes"
max_width = 1000
max_height = 1000
image_delay = 100
image_filter = "nearest"
image_quality = 50

[opener]
edit = [
  { run = 'hx "$@"', block = true, for = "unix" },
]
