[mgr]
ratio = [1,4,2]
sort_by = "extension"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "mtime"
show_hidden = true
show_symlink = true

[preview]
wrap = "yes"
image_filter = "nearest"

[opener]
edit = [
  { run = 'hx "$@"', block = true, for = "unix" },
]
