# ~/.config/helix/config.toml

theme = "theme"

[editor]
line-number = "relative"          # show relative line numbers
cursorline = true                 # highlight current line
auto-completion = true            # enable autocomplete
auto-format = true                # format on save if possible
scrolloff = 5                     # keep context around cursor
true-color = true                 # full 24-bit color support
idle-timeout = 200                # reduce delay for features (ms)
bufferline = "multiple"           # show open buffers

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true                     # show indentation guides
character = "│"
skip-levels = 1

[editor.file-picker]
hidden = false                    # show hidden files

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-type"]

